baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Tag+'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo.png"
  desktop: "images/logo/logo.png"
  desktop_height: "36px"
footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Tag+"
  meta_og_type: "website"
  meta_og_url: "https://tagplus.vn"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Tag+ offers software development outsourcing and supports your business with one-stop IT solutions."
  meta_twitter_card: "summary"
  meta_twitter_site: "@tagplusvn"
  meta_twitter_creator: "@tagplusvn"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
